development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: feedback_fruits_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: feedback_fruits_production
